(function(){
  const Dashboard = window.Dashboard;
  const { BaseSection, registerSection, set, avg, freq, mkChart, CC } = Dashboard;

  class TicSection extends BaseSection {
    constructor(){
      super('tic', 'TIC');
      this.filterSource = false;
      this.filterKey = 'Codigo';
      this.data = [
        {"Codigo":"E-0001","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"Sí","Educación TIC2":"Sí","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"Sí","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":8,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":8,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0002","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"Sí","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":7,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":2,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0003","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":6,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":2,"Accesibilidad servicios digitales":3,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0004","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"Sí","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":10,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":0,"Accesibilidad servicios digitales":9,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0005","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":1,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":5,"Accesibilidad servicios digitales":5,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0006","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":8,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":7,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0007","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":5,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":99,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0008","Entretenimiento TIC1":null,"Trabajo TIC1":null,"Educación TIC1":null,"Transporte TIC1":null,"No tiene el dispositivo TIC1":null,"No accede a internet a través del dispositivo TIC1":null,"Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":null,"Trabajo TIC3":null,"Educación TIC3":null,"Transporte TIC3":null,"No tiene el dispositivo TIC3":null,"No accede a internet a través del dispositivo TIC3":null,"Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":null,"Trabajo TIC5":null,"Educación TIC5":null,"Transporte TIC5":null,"No tiene el dispositivo TIC5":null,"No accede a internet a través del dispositivo TIC5":null,"Entretenimiento TIC6":null,"Trabajo TIC6":null,"Educación TIC6":null,"Transporte TIC6":null,"No tiene el dispositivo TIC6":null,"No accede a internet a través del dispositivo TIC6":null,"Entretenimiento TIC7":null,"Trabajo TIC7":null,"Educación TIC7":null,"Transporte TIC7":null,"No tiene el dispositivo TIC7":null,"No accede a internet a través del dispositivo TIC7":null,"Entretenimiento TIC8":null,"Trabajo TIC8":null,"Educación TIC8":null,"Transporte TIC8":null,"No tiene el dispositivo TIC8":null,"No accede a internet a través del dispositivo TIC8":null,"Satisfacción conexión internet":4,"Uso canales digitales trámites":"No","Confianza plataformas participación":99,"Accesibilidad servicios digitales":99,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0009","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"Sí","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":null,"Trabajo TIC3":null,"Educación TIC3":null,"Transporte TIC3":null,"No tiene el dispositivo TIC3":null,"No accede a internet a través del dispositivo TIC3":null,"Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":null,"Trabajo TIC5":null,"Educación TIC5":null,"Transporte TIC5":null,"No tiene el dispositivo TIC5":null,"No accede a internet a través del dispositivo TIC5":null,"Entretenimiento TIC6":null,"Trabajo TIC6":null,"Educación TIC6":null,"Transporte TIC6":null,"No tiene el dispositivo TIC6":null,"No accede a internet a través del dispositivo TIC6":null,"Entretenimiento TIC7":null,"Trabajo TIC7":null,"Educación TIC7":null,"Transporte TIC7":null,"No tiene el dispositivo TIC7":null,"No accede a internet a través del dispositivo TIC7":null,"Entretenimiento TIC8":null,"Trabajo TIC8":null,"Educación TIC8":null,"Transporte TIC8":null,"No tiene el dispositivo TIC8":null,"No accede a internet a través del dispositivo TIC8":null,"Satisfacción conexión internet":5,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":99,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0010","Entretenimiento TIC1":"Sí","Trabajo TIC1":"No","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":8,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":3,"Accesibilidad servicios digitales":10,"Conoce datos abiertos":"Sí"},
        {"Codigo":"E-0011","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"Sí","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":5,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":7,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0012","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"Sí","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"Sí","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"No","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":7,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":2,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0013","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":null,"Trabajo TIC3":null,"Educación TIC3":null,"Transporte TIC3":null,"No tiene el dispositivo TIC3":null,"No accede a internet a través del dispositivo TIC3":null,"Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":null,"Trabajo TIC5":null,"Educación TIC5":null,"Transporte TIC5":null,"No tiene el dispositivo TIC5":null,"No accede a internet a través del dispositivo TIC5":null,"Entretenimiento TIC6":null,"Trabajo TIC6":null,"Educación TIC6":null,"Transporte TIC6":null,"No tiene el dispositivo TIC6":null,"No accede a internet a través del dispositivo TIC6":null,"Entretenimiento TIC7":null,"Trabajo TIC7":null,"Educación TIC7":null,"Transporte TIC7":null,"No tiene el dispositivo TIC7":null,"No accede a internet a través del dispositivo TIC7":null,"Entretenimiento TIC8":null,"Trabajo TIC8":null,"Educación TIC8":null,"Transporte TIC8":null,"No tiene el dispositivo TIC8":null,"No accede a internet a través del dispositivo TIC8":null,"Satisfacción conexión internet":8,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":2,"Accesibilidad servicios digitales":5,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0014","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"No","Trabajo TIC2":"No","Educación TIC2":"Sí","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":3,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":7,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0015","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"Sí","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"Sí","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"No","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":6,"Uso canales digitales trámites":"No","Confianza plataformas participación":0,"Accesibilidad servicios digitales":0,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0016","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":null,"Trabajo TIC3":null,"Educación TIC3":null,"Transporte TIC3":null,"No tiene el dispositivo TIC3":null,"No accede a internet a través del dispositivo TIC3":null,"Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"No","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"Sí","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"No","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":10,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":1,"Accesibilidad servicios digitales":1,"Conoce datos abiertos":"No"},
        {"Codigo":"E-0017","Entretenimiento TIC1":"No","Trabajo TIC1":"Sí","Educación TIC1":"No","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"Sí","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"No","Transporte TIC5":"No","No tiene el dispositivo TIC5":"Sí","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":10,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":4,"Accesibilidad servicios digitales":1,"Conoce datos abiertos":"Sí"},
        {"Codigo":"E-0018","Entretenimiento TIC1":"No","Trabajo TIC1":"No","Educación TIC1":"Sí","Transporte TIC1":"No","No tiene el dispositivo TIC1":"No","No accede a internet a través del dispositivo TIC1":"No","Entretenimiento TIC2":"Sí","Trabajo TIC2":"No","Educación TIC2":"No","Transporte TIC2":"No","No tiene el dispositivo TIC2":"No","No accede a internet a través del dispositivo TIC2":"No","Entretenimiento TIC3":"No","Trabajo TIC3":"No","Educación TIC3":"No","Transporte TIC3":"No","No tiene el dispositivo TIC3":"No","No accede a internet a través del dispositivo TIC3":"No","Entretenimiento TIC4":"Sí","Trabajo TIC4":"No","Educación TIC4":"No","Transporte TIC4":"No","No tiene el dispositivo TIC4":"No","No accede a internet a través del dispositivo TIC4":"No","Entretenimiento TIC5":"No","Trabajo TIC5":"No","Educación TIC5":"Sí","Transporte TIC5":"No","No tiene el dispositivo TIC5":"No","No accede a internet a través del dispositivo TIC5":"No","Entretenimiento TIC6":"No","Trabajo TIC6":"No","Educación TIC6":"No","Transporte TIC6":"No","No tiene el dispositivo TIC6":"Sí","No accede a internet a través del dispositivo TIC6":"No","Entretenimiento TIC7":"No","Trabajo TIC7":"No","Educación TIC7":"No","Transporte TIC7":"No","No tiene el dispositivo TIC7":"Sí","No accede a internet a través del dispositivo TIC7":"No","Entretenimiento TIC8":"No","Trabajo TIC8":"No","Educación TIC8":"No","Transporte TIC8":"No","No tiene el dispositivo TIC8":"Sí","No accede a internet a través del dispositivo TIC8":"No","Satisfacción conexión internet":7,"Uso canales digitales trámites":"Sí","Confianza plataformas participación":99,"Accesibilidad servicios digitales":4,"Conoce datos abiertos":"No"}
      ];
    }

    getHtml(isActive){
      return `
<div class="sec${isActive ? ' active' : ''}" id="s-tic">
  <div class="sech"><h2>📱 Tecnologías de la Información</h2><p>Uso de dispositivos, trámites digitales y confianza en plataformas</p></div>
  <div class="kpi"><div class="v" id="tic-sat">—</div><div class="l">Satisfacción promedio con la conexión a internet</div></div>
  <div class="g2">
    <div class="card"><div class="ct">Principal uso del computador</div><div class="cw t"><canvas id="tic-computador"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso del celular</div><div class="cw t"><canvas id="tic-celular"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso de la tableta</div><div class="cw t"><canvas id="tic-tableta"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso del televisor</div><div class="cw t"><canvas id="tic-tv"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso de consola de videojuegos</div><div class="cw t"><canvas id="tic-consola"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso de lectores de libros electrónicos</div><div class="cw t"><canvas id="tic-lector"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso del reloj inteligente</div><div class="cw t"><canvas id="tic-reloj"></canvas></div></div>
    <div class="card"><div class="ct">Principal uso del asistente virtual del hogar</div><div class="cw t"><canvas id="tic-asistente"></canvas></div></div>
  </div>
  <div class="g2">
    <div class="card"><div class="ct">En los últimos 12 meses, ¿ha utilizado canales digitales para trámites?</div><div class="cw"><canvas id="tic-tramites"></canvas></div></div>
    <div class="card"><div class="ct">Confianza en plataformas digitales de participación ciudadana (0-10)</div><div class="cw"><canvas id="tic-confianza"></canvas></div></div>
    <div class="card"><div class="ct">Accesibilidad y facilidad de servicios digitales del gobierno local (0-10)</div><div class="cw"><canvas id="tic-accesibilidad"></canvas></div></div>
    <div class="card"><div class="ct">¿Conoce plataformas y sitios web de datos abiertos?</div><div class="cw"><canvas id="tic-datos"></canvas></div></div>
  </div>
</div>`;
    }

    render(data, n){
      // Función para promediar numéricos
      const num = v => (v === 99 || v === null || v === undefined || v === 'NA' || v === '') ? null : +v;
      const avgArr = arr => { const valid = arr.filter(x => x !== null && !isNaN(x)); return valid.length ? (valid.reduce((a,b) => a+b, 0) / valid.length).toFixed(1) : '—'; };

      // Tarjeta de satisfacción conexión internet
      const satVal = data.map(r => num(r["Satisfacción conexión internet"])).filter(v => v !== null);
      const satProm = satVal.length ? (satVal.reduce((a,b) => a+b, 0) / satVal.length).toFixed(1) : '—';
      set('tic-sat', satProm);

      // Helper para graficar usos de un dispositivo (TICx)
      function renderDevice(deviceId, prefix, deviceName) {
        const categorias = ["Entretenimiento", "Trabajo", "Educación", "Transporte", "No tiene el dispositivo", "No accede a internet a través del dispositivo"];
        const colNames = categorias.map(cat => `${cat} ${prefix}`);
        const counts = colNames.map(col => data.filter(r => r[col] === 'Sí').length);
        mkChart(deviceId, 'bar', categorias, [{
          label: 'Personas',
          data: counts,
          backgroundColor: '#0ea5e9',
          borderRadius: 5,
          borderWidth: 0
        }], { indexAxis: 'y', legend: { display: true, position: 'top' } });
      }

      renderDevice('tic-computador', 'TIC1', 'computador');
      renderDevice('tic-celular', 'TIC2', 'celular');
      renderDevice('tic-tableta', 'TIC3', 'tableta');
      renderDevice('tic-tv', 'TIC4', 'televisor');
      renderDevice('tic-consola', 'TIC5', 'consola de videojuegos');
      renderDevice('tic-lector', 'TIC6', 'lector de libros electrónicos');
      renderDevice('tic-reloj', 'TIC7', 'reloj inteligente');
      renderDevice('tic-asistente', 'TIC8', 'asistente virtual del hogar');

      // Uso canales digitales para trámites
      const tramitesFreq = freq(data, "Uso canales digitales trámites");
      const tramKeys = Object.keys(tramitesFreq);
      mkChart('tic-tramites', 'doughnut', tramKeys, [{
        data: tramKeys.map(k => tramitesFreq[k]),
        backgroundColor: CC,
        borderWidth: 0
      }], { legend: { display: true, position: 'top' } });

      // Confianza plataformas (0-10)
      const confVal = data.map(r => num(r["Confianza plataformas participación"])).filter(v => v !== null);
      const confFreq = {};
      confVal.forEach(v => { confFreq[v] = (confFreq[v] || 0) + 1; });
      const confPuntos = Array.from({length: 11}, (_, i) => i);
      const confFrecuencias = confPuntos.map(p => confFreq[p] || 0);
      mkChart('tic-confianza', 'bar', confPuntos.map(p => p.toString()), [{
        label: 'Personas',
        data: confFrecuencias,
        backgroundColor: '#f59e0b',
        borderRadius: 5,
        borderWidth: 0
      }], { legend: { display: true, position: 'top' } });

      // Accesibilidad servicios digitales (0-10)
      const accVal = data.map(r => num(r["Accesibilidad servicios digitales"])).filter(v => v !== null);
      const accFreq = {};
      accVal.forEach(v => { accFreq[v] = (accFreq[v] || 0) + 1; });
      const accPuntos = Array.from({length: 11}, (_, i) => i);
      const accFrecuencias = accPuntos.map(p => accFreq[p] || 0);
      mkChart('tic-accesibilidad', 'bar', accPuntos.map(p => p.toString()), [{
        label: 'Personas',
        data: accFrecuencias,
        backgroundColor: '#8b5cf6',
        borderRadius: 5,
        borderWidth: 0
      }], { legend: { display: true, position: 'top' } });

      // Conocimiento de datos abiertos
      const datosFreq = freq(data, "Conoce datos abiertos");
      const datosKeys = Object.keys(datosFreq);
      mkChart('tic-datos', 'bar', datosKeys, [{
        label: 'Personas',
        data: datosKeys.map(k => datosFreq[k]),
        backgroundColor: '#10b981',
        borderRadius: 5,
        borderWidth: 0
      }], { legend: { display: true, position: 'top' } });
    }
  }

  registerSection(new TicSection());
})();