(function(){
  const Dashboard = window.Dashboard;
  const { BaseSection, registerSection, set, avg2, pct, freq, mkChart, CC } = Dashboard;
  class SaludSection extends BaseSection {
    constructor(){
      super('salud','Salud');
      this.filterSource = false;
      this.filterKey = 'Codigo';
      this.data = [
        {"Codigo":"E-0001","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Buena","Días promedio en los que no gozó de buena salud":0,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Bastante","Días promedios impedidos para realizar activades personales y de recreación por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":4,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":0,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":3,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":0,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":0,"Nervioso/ansioso SAL2":0,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":2,"Dificultad para relajarse SAL2":2,"Inquieto SAL2":0,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":1,"Cansado SAL3":0,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":5,"Minutos promedio actividad física":60,"Altura promedio":1.8,"Peso promedio":85,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":8,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0002","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Mala","Días promedio en los que no gozó de buena salud":25,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Moderadamente","Días promedios impedidos para realizar activades personales y de recreación por problemas de salud física y mental":20,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":3,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":4,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":4,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":1,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":2,"Inquieto SAL2":1,"Irritado facilmente SAL2":3,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":1,"Se ha sentido decaído(a) SAL3":1,"Dificultad para dormir SAL3":2,"Cansado SAL3":3,"Sin apetito o ha comido en exceso SAL3":1,"Fracasado SAL3":3,"Dificultad para concentrarse SAL 3":3,"Se ha sentido lento – muy inquieto(a) SAL3":1,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":2,"Minutos promedio actividad física":60,"Altura promedio":1.62,"Peso promedio":86,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"No, varía mucho"},
        {"Codigo":"E-0003","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":10,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Moderadamente","Días promedios impedidos para realizar activades personales y de recreación por problemas de salud física y mental":15,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":0,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":1,"Poco interés o placer en hacer cosas SAL3":1,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":1,"Fracasado SAL3":1,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":"NA","¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.64,"Peso promedio":63,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":9,"¿En general, se acuesta y se levanta en el mismo horario?":"No, varía mucho"},
        {"Codigo":"E-0004","Tipo de afiliación a salud":"Medicina prepagada","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":3,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreación por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":0,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":0,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":4,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":0,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":0,"Nervioso/ansioso SAL2":0,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":0,"Dificultad para relajarse SAL2":0,"Inquieto SAL2":0,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":1,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.6,"Peso promedio":58,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":8,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0005","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Muy buena","Días promedio en los que no gozó de buena salud":0,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":0,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":0,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":0,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":4,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":0,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":3,"Preocupación extrema SAL2":0,"Dificultad para relajarse SAL2":0,"Inquieto SAL2":0,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":0,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"No","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.5,"Peso promedio":64,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0006","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Buena","Días promedio en los que no gozó de buena salud":99,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":0,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":1,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenia que hacer? SAL1":1,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":4,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":0,"incapaz de no estar preocupado SAL2":3,"Preocupación extrema SAL2":0,"Dificultad para relajarse SAL2":0,"Inquieto SAL2":0,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":1,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"No","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":3,"Minutos promedio actividad física":"NA","Altura promedio":1.67,"Peso promedio":75,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0007","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Mala","Días promedio en los que no gozó de buena salud":20,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Bastante","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":3,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":3,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":4,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":2,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":2,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":2,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":3,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":2,"Nervioso/ansioso SAL2":3,"incapaz de no estar preocupado SAL2":3,"Preocupación extrema SAL2":3,"Dificultad para relajarse SAL2":3,"Inquieto SAL2":3,"Irritado facilmente SAL2":3,"Sentido miedo SAL2":3,"Poco interés o placer en hacer cosas SAL3":3,"Se ha sentido decaído(a) SAL3":3,"Dificultad para dormir SAL3":3,"Cansado SAL3":3,"Sin apetito o ha comido en exceso SAL3":3,"Fracasado SAL3":3,"Dificultad para concentrarse SAL 3":3,"Se ha sentido lento – muy inquieto(a) SAL3":3,"Pensamientos que atenten su integridad SAL3":2,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":5,"Minutos promedio actividad física":90,"Altura promedio":1.68,"Peso promedio":72,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0008","Tipo de afiliación a salud":"Medicina prepagada","Percepción del estado de salud":"Mala","Días promedio en los que no gozó de buena salud":30,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":2,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":2,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":2,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":2,"Nervioso/ansioso SAL2":0,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":0,"Dificultad para relajarse SAL2":0,"Inquieto SAL2":1,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":3,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":1,"Cansado SAL3":3,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"No","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.65,"Peso promedio":80,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"No","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0009","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Mala","Días promedio en los que no gozó de buena salud":30,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":0,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":2,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":2,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":1,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":1,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":1,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":1,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":1,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"No","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.73,"Peso promedio":73,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0010","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":0,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":"NA","¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":0,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":3,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":3,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":2,"Inquieto SAL2":0,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":2,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":3,"Cansado SAL3":2,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":2,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":2,"Minutos promedio actividad física":60,"Altura promedio":1.67,"Peso promedio":78,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"No","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0011","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":2,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":1,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":0,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":0,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":0,"Nervioso/ansioso SAL2":0,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":0,"Dificultad para relajarse SAL2":0,"Inquieto SAL2":0,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":1,"Minutos promedio actividad física":120,"Altura promedio":1.7,"Peso promedio":82,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":8,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0012","Tipo de afiliación a salud":"Subsidiado (Sisbén / Sisben)","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":5,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":3,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":3,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":4,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":3,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":1,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":0,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":1,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":1,"Dificultad para dormir SAL3":1,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":1,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.83,"Peso promedio":70,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0013","Tipo de afiliación a salud":"Subsidiado (Sisbén / Sisben)","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":3,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":2,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":1,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":3,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":1,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":3,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":3,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":0,"Irritado facilmente SAL2":2,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":1,"Cansado SAL3":2,"Sin apetito o ha comido en exceso SAL3":1,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":1,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":1,"Minutos promedio actividad física":30,"Altura promedio":1.6,"Peso promedio":63,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"No","Horas promedio de sueño":7,"¿En general, se acuesta y se levanta en el mismo horario?":"No, varía mucho"},
        {"Codigo":"E-0014","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Buena","Días promedio en los que no gozó de buena salud":6,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Bastante","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":10,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":4,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":3,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":2,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":3,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":3,"Nervioso/ansioso SAL2":3,"incapaz de no estar preocupado SAL2":3,"Preocupación extrema SAL2":3,"Dificultad para relajarse SAL2":3,"Inquieto SAL2":3,"Irritado facilmente SAL2":3,"Sentido miedo SAL2":3,"Poco interés o placer en hacer cosas SAL3":2,"Se ha sentido decaído(a) SAL3":3,"Dificultad para dormir SAL3":3,"Cansado SAL3":3,"Sin apetito o ha comido en exceso SAL3":2,"Fracasado SAL3":3,"Dificultad para concentrarse SAL 3":2,"Se ha sentido lento – muy inquieto(a) SAL3":3,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.73,"Peso promedio":60,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0015","Tipo de afiliación a salud":"No sabe / No responde","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":99,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Moderadamente","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":0,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":1,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":4,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":2,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":3,"incapaz de no estar preocupado SAL2":2,"Preocupación extrema SAL2":3,"Dificultad para relajarse SAL2":2,"Inquieto SAL2":3,"Irritado facilmente SAL2":2,"Sentido miedo SAL2":3,"Poco interés o placer en hacer cosas SAL3":2,"Se ha sentido decaído(a) SAL3":2,"Dificultad para dormir SAL3":3,"Cansado SAL3":2,"Sin apetito o ha comido en exceso SAL3":3,"Fracasado SAL3":2,"Dificultad para concentrarse SAL 3":"NA","Se ha sentido lento – muy inquieto(a) SAL3":"NA","Pensamientos que atenten su integridad SAL3":2,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"Sí","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.87,"Peso promedio":100,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"No","Horas promedio de sueño":8,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"},
        {"Codigo":"E-0016","Tipo de afiliación a salud":"No sabe / No responde","Percepción del estado de salud":"Regular","Días promedio en los que no gozó de buena salud":5,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Nada","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":1,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":2,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":3,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":1,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":3,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":2,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":3,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":0,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":3,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":1,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":4,"Minutos promedio actividad física":60,"Altura promedio":1.65,"Peso promedio":64,"Conforme con peso actual SAL4":"No","Hace algo para modificar peso SAL4":"Sí","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0017","Tipo de afiliación a salud":"Contributivo (EPS cotizante)","Percepción del estado de salud":"Buena","Días promedio en los que no gozó de buena salud":2,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":1,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":0,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":2,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":1,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":3,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":1,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":3,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":3,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":1,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":1,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":1,"Dificultad para relajarse SAL2":1,"Inquieto SAL2":1,"Irritado facilmente SAL2":0,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":1,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":1,"Cansado SAL3":1,"Sin apetito o ha comido en exceso SAL3":0,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":0,"Se ha sentido lento – muy inquieto(a) SAL3":0,"Pensamientos que atenten su integridad SAL3":0,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"Sí","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"Sí","Días promedio actividad física":5,"Minutos promedio actividad física":90,"Altura promedio":1.6,"Peso promedio":51,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":6,"¿En general, se acuesta y se levanta en el mismo horario?":"Sí, siempre en el mismo horario"},
        {"Codigo":"E-0018","Tipo de afiliación a salud":"Subsidiado (Sisbén / Sisben)","Percepción del estado de salud":"Buena","Días promedio en los que no gozó de buena salud":30,"¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)":"Un poco","Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental":0,"¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1":1,"¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1":1,"¿Con qué frecuencia ha sentido nervioso o estresado? SAL1":1,"¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1":4,"¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1":4,"¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1":4,"¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1":2,"¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1":2,"¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1":1,"¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1":0,"Nervioso/ansioso SAL2":1,"incapaz de no estar preocupado SAL2":0,"Preocupación extrema SAL2":2,"Dificultad para relajarse SAL2":2,"Inquieto SAL2":2,"Irritado facilmente SAL2":1,"Sentido miedo SAL2":0,"Poco interés o placer en hacer cosas SAL3":2,"Se ha sentido decaído(a) SAL3":0,"Dificultad para dormir SAL3":0,"Cansado SAL3":2,"Sin apetito o ha comido en exceso SAL3":2,"Fracasado SAL3":0,"Dificultad para concentrarse SAL 3":2,"Se ha sentido lento – muy inquieto(a) SAL3":3,"Pensamientos que atenten su integridad SAL3":3,"¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4":"No","¿Usted fuma? SAL4":"No","Realiza actividad física SAL4":"No","Días promedio actividad física":"NA","Minutos promedio actividad física":"NA","Altura promedio":1.74,"Peso promedio":64,"Conforme con peso actual SAL4":"Sí","Hace algo para modificar peso SAL4":"NA","Horas promedio de sueño":10,"¿En general, se acuesta y se levanta en el mismo horario?":"Casi siempre"}
      ];
    }
    getHtml(isActive){
      return `
<div class="sec${isActive ? ' active' : ''}" id="s-salud">
  <div class="sech"><h2>🏥 Salud</h2><p>Salud física, mental y bienestar psicológico</p></div>
  <div class="g4">
    <div class="kpi"><div class="v" id="sa-total">18</div><div class="l">Total</div></div>
    <div class="kpi"><div class="v" id="sa-dias-mal-salud">—</div><div class="l">Días sin buena salud (prom)</div></div>
    <div class="kpi"><div class="v" id="sa-dias-impedidos">—</div><div class="l">Días impedidos (prom)</div></div>
    <div class="kpi"><div class="v" id="sa-dias-actividad">—</div><div class="l">Días actividad física</div></div>
    <div class="kpi"><div class="v" id="sa-minutos">—</div><div class="l">Minutos actividad física</div></div>
    <div class="kpi"><div class="v" id="sa-altura">—</div><div class="l">Altura promedio (m)</div></div>
    <div class="kpi"><div class="v" id="sa-peso">—</div><div class="l">Peso promedio (kg)</div></div>
    <div class="kpi"><div class="v" id="sa-sueno">—</div><div class="l">Horas de sueño (prom)</div></div>
  </div>
  <div class="g2">
    <div class="card"><div class="ct">Tipo de afiliación a salud</div><div class="cw"><canvas id="c-afil"></canvas></div></div>
    <div class="card"><div class="ct">Percepción del estado de salud</div><div class="cw"><canvas id="c-percepcion"></canvas></div></div>
    <div class="card"><div class="ct">¿En qué medida su salud mental se ha visto afectada?</div><div class="cw"><canvas id="c-salud-mental"></canvas></div></div>
    <div class="card"><div class="ct">¿Se acuesta y levanta en el mismo horario?</div><div class="cw"><canvas id="c-horario"></canvas></div></div>
    <div class="card"><div class="ct">Estrés percibido PSS-10 (SAL1)</div><div class="cw t"><canvas id="c-sal1"></canvas></div></div>
    <div class="card"><div class="ct">Emociones últimas 2 semanas (SAL2)</div><div class="cw t"><canvas id="c-sal2"></canvas></div></div>
    <div class="card"><div class="ct">Malestar últimas 3 semanas (SAL3)</div><div class="cw t"><canvas id="c-sal3"></canvas></div></div>
    <div class="card"><div class="ct">Condiciones de salud física y mental (SAL4)</div><div class="cw"><canvas id="c-sal4"></canvas></div></div>
  </div>
</div>`;
    }
    render(data, n){
      set('sa-total', n);
      const num = v => (v === null || v === undefined || v === 'NA' || v === 98 || v === 99) ? null : +v;
      const avg = arr => { const v = arr.filter(x => x !== null && !isNaN(x)); return v.length ? (v.reduce((a,b) => a+b, 0) / v.length).toFixed(1) : '—'; };
      const diasMal = avg(data.map(r => num(r["Días promedio en los que no gozó de buena salud"])).filter(v => v !== null));
      set('sa-dias-mal-salud', diasMal);
      const diasImpedidos = avg(data.map(r => num(r["Días promedios impedidos para realizar activades personales y de recreation por problemas de salud física y mental"])).filter(v => v !== null));
      set('sa-dias-impedidos', diasImpedidos);
      const diasAct = avg(data.map(r => num(r["Días promedio actividad física"])).filter(v => v !== null));
      set('sa-dias-actividad', diasAct);
      const minutos = avg(data.map(r => num(r["Minutos promedio actividad física"])).filter(v => v !== null));
      set('sa-minutos', minutos);
      const altura = avg(data.map(r => num(r["Altura promedio"])).filter(v => v !== null));
      set('sa-altura', altura);
      const peso = avg(data.map(r => num(r["Peso promedio"])).filter(v => v !== null));
      set('sa-peso', peso);
      const sueno = avg(data.map(r => num(r["Horas promedio de sueño"])).filter(v => v !== null));
      set('sa-sueno', sueno);
      const afilFm = freq(data, "Tipo de afiliación a salud");
      const afilK = Object.keys(afilFm);
      mkChart('c-afil', 'bar', afilK, [{label: 'Personas', data: afilK.map(k => afilFm[k]), backgroundColor: CC, borderRadius: 5, borderWidth: 0}]);
      const percepFm = freq(data, "Percepción del estado de salud");
      const percepMap = {'Muy buena': 1, 'Buena': 2, 'Regular': 3, 'Mala': 4, 'Muy mala': 5};
      const percepK = Object.keys(percepFm).sort((a,b) => percepMap[a] - percepMap[b]);
      mkChart('c-percepcion', 'bar', percepK, [{label: 'Personas', data: percepK.map(k => percepFm[k]), backgroundColor: '#10b981', borderRadius: 5, borderWidth: 0}]);
      const saludMentalFm = freq(data, "¿en qué medida su salud mental se ha visto afectada por tensión, depresión u otros problemas emocionales? - (CDC 5)");
      const saludMentalMap = {'Nada': 1, 'Un poco': 2, 'Moderadamente': 3, 'Bastante': 4};
      const smK = Object.keys(saludMentalFm).sort((a,b) => (saludMentalMap[a] || 99) - (saludMentalMap[b] || 99));
      mkChart('c-salud-mental', 'doughnut', smK, [{data: smK.map(k => saludMentalFm[k]), backgroundColor: CC, borderWidth: 0}], {legend: true});
      const horarioFm = freq(data, "¿En general, se acuesta y se levanta en el mismo horario?");
      const horarioK = Object.keys(horarioFm);
      mkChart('c-horario', 'bar', horarioK, [{label: 'Personas', data: horarioK.map(k => horarioFm[k]), backgroundColor: '#06b6d4', borderRadius: 5, borderWidth: 0}]);
      const sal1Cols = [
        "¿Con qué frecuencia ha estado afectado por algo que ha ocurrido inesperadamente? SAL1",
        "¿Con qué frecuencia se ha sentido incapaz de controlar las cosas importantes en su vida? SAL1",
        "¿Con qué frecuencia ha sentido nervioso o estresado? SAL1",
        "¿Con qué frecuencia ha estado Sí sobre su capacidad para manejar sus problemas personales? SAL1",
        "¿Con qué frecuencia ha sentido que las cosas le van bien? SAL1",
        "¿Con qué frecuencia ha sentido que no podía afrontar todas las cosas que tenía que hacer? SAL1",
        "¿Con qué frecuencia ha podido controlar las dificultades de su vida? SAL1",
        "¿Con qué frecuencia ha sentido que tenía todo bajo control? SAL1",
        "¿Con qué frecuencia ha estado enojado porque las cosas que le han ocurrido estaban fuera de su control? SAL1",
        "¿Con qué frecuencia ha sentido que las dificultades se acumulan tanto que no puede superarlas? SAL1"
      ];
      const sal1Labs = ['Afect. inesperad.', 'Incapaz controlar', 'Nervioso', 'Seguro sí mismo', 'Cosas van bien', 'No podía afrontar', 'Control dificultades', 'Todo bajo control', 'Enojado sin control', 'Dificultades acumulan'];
      mkChart('c-sal1', 'bar', sal1Labs, [{label: 'Promedio', data: sal1Cols.map(c => avg(data.map(r => num(r[c])).filter(v => v !== null))), backgroundColor: '#f59e0b', borderRadius: 5, borderWidth: 0}], {indexAxis: 'y'});
      const sal2Cols = ["Nervioso/ansioso SAL2", "incapaz de no estar preocupado SAL2", "Preocupación extrema SAL2", "Dificultad para relajarse SAL2", "Inquieto SAL2", "Irritado facilmente SAL2", "Sentido miedo SAL2"];
      const sal2Labs = ['Nervioso/ansioso', 'Incapaz controlar', 'Preocupación ext.', 'Difícil relajarse', 'Inquieto', 'Irritable', 'Miedo'];
      mkChart('c-sal2', 'bar', sal2Labs, [{label: 'Promedio', data: sal2Cols.map(c => avg(data.map(r => num(r[c])).filter(v => v !== null))), backgroundColor: '#8b5cf6', borderRadius: 5, borderWidth: 0}], {indexAxis: 'y'});
      const sal3Cols = ["Poco interés o placer en hacer cosas SAL3", "Se ha sentido decaído(a) SAL3", "Dificultad para dormir SAL3", "Cansado SAL3", "Sin apetito o ha comido en exceso SAL3", "Fracasado SAL3", "Dificultad para concentrarse SAL 3", "Se ha sentido lento – muy inquieto(a) SAL3", "Pensamientos que atenten su integridad SAL3"];
      const sal3Labs = ['Poco interés', 'Decaído', 'Sueño alterado', 'Cansado', 'Apetito alterado', 'Fracasado', 'Concentración', 'Movimiento alterado', 'Pensamientos daño'];
      mkChart('c-sal3', 'bar', sal3Labs, [{label: 'Promedio', data: sal3Cols.map(c => avg(data.map(r => num(r[c])).filter(v => v !== null))), backgroundColor: '#ef4444', borderRadius: 5, borderWidth: 0}], {indexAxis: 'y'});
      const sal4Cols = ["¿Usted cree que alguna vez ha tenido problemas con su salud mental? SAL4", "¿Usted fuma? SAL4", "Realiza actividad física SAL4", "Conforme con peso actual SAL4", "Hace algo para modificar peso SAL4"];
      const sal4Labs = ['Prob. salud mental', 'Fuma', 'Actividad física', 'Conforme con peso', 'Modifica peso'];
      const sal4Data = sal4Cols.map(col => {
        const siCount = data.filter(r => r[col] === 'Sí').length;
        return n > 0 ? Math.round(siCount / n * 100) : 0;
      });
      mkChart('c-sal4', 'bar', sal4Labs, [{label: '% Sí', data: sal4Data, backgroundColor: '#14b8a6', borderRadius: 5, borderWidth: 0}]);
    }
  }
  registerSection(new SaludSection());
})();